name: 'Custom LLM Code Reviewer'
description: 'Review code using OpenAI-compatible LLMs (Ollama, vLLM, DeepSeek, etc.)'
inputs:
  # 변경 1: Gemini Key 대신 LLM 접속 정보 3가지를 입력받음
  llm_api_key:
    description: 'LLM API Key (Optional for local models)'
    required: false
    default: 'EMPTY'
    
  # 기존 유지
  github_token:
    description: 'GitHub Token'
    required: true
  pr_number:
    description: 'PR Number'
    required: true
  discord_webhook_url:
    description: 'Discord Webhook URL'
    required: false

runs:
  using: "composite"
  steps:
    # 변경 2: google-generativeai 제거 -> openai 추가
    - name: Install Dependencies
      run: python3 -m pip install openai PyGithub requests
      shell: bash

    # 변경 3: 환경 변수 매핑 변경 (GEMINI_API_KEY 삭제 -> LLM_* 추가)
    - name: Run Review Script
      run: python ${{ github.action_path }}/ai_reviewer.py
      shell: bash
      env:
        LLM_API_KEY: ${{ inputs.llm_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ inputs.pr_number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        DISCORD_WEBHOOK_URL: ${{ inputs.discord_webhook_url }}