name: 'Custom LLM Code Reviewer'
description: 'Review code using Google Gemini'
inputs:
  gemini_api_key:
    description: 'Google Gemini API Key'
    required: true
    
  github_token:
    description: 'GitHub Token'
    required: true
  pr_number:
    description: 'PR Number'
    required: true
  discord_webhook_url:
    description: 'Discord Webhook URL'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup and Run AI Reviewer
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ inputs.pr_number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        DISCORD_WEBHOOK_URL: ${{ inputs.discord_webhook_url }}
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        
        # ✅ 변경: openai 제거 -> google-generativeai 설치
        pip install google-generativeai PyGithub requests
        
        python -u ${{ github.action_path }}/ai_reviewer.py