name: 'Gemini AI Code Reviewer'
description: 'Review code using Gemini AI'
inputs:
  gemini_api_key:  # 외부에서 받아올 입력값 1
    description: 'Google Gemini API Key'
    required: true
  github_token:    # 외부에서 받아올 입력값 2
    description: 'GitHub Token'
    required: true
  pr_number:       # 외부에서 받아올 입력값 3
    description: 'PR Number'
    required: true
  discord_webhook_url:
    description: 'Discord Webhook URL'
    required: false

runs:
  using: "composite" # 이것이 핵심!
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Dependencies
      run: pip install google-generativeai PyGithub requests
      shell: bash # composite에서는 shell 명시 필수

    # 파이썬 스크립트 실행 (입력받은 값을 환경변수로 넘김)
    - name: Run Review Script
      run: python ${{ github.action_path }}/ai_reviewer.py
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ inputs.pr_number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        DISCORD_WEBHOOK_URL: ${{ inputs.discord_webhook_url }}